const customerCreatedResponse = {
  isError: false,
  data: {
    birthDate: null,
    changedBy: null,
    createDate: "2025-01-07T02:04:20.3139009-06:00",
    failedPasswordAttemptCount: 0,
    firstName: "Tanishq",
    id: 49083,
    isEmployee: null,
    lastActivityDate: null,
    lastName: null,
    memberCloseDate: null,
    memberCreateDate: "2025-01-07T02:04:20.2932156-06:00",
    memberStatus: "PreEnrolled",
    mergedToMember: null,
    middleName: null,
    namePrefix: null,
    nameSuffix: null,
    newStatus: null,
    newStatusEffectiveDate: "2025-01-07T02:04:20.2932156-06:00",
    passwordChangeRequired: false,
    passwordExpireDate: null,
    preferredLanguage: null,
    email: "sample@gmail.com",
    phone: null,
    zipCode: null,
    resetCode: null,
    resetCodeDate: null,
    statusChangeDate: "2025-01-07T02:04:20.2932156-06:00",
    statusChangeReason: null,
    updateDate: "2025-01-07T02:04:20.5286932-06:00",
    username: null,
    alternateId: null,
    cards: [
      {
        cardType: 1,
        changedBy: null,
        createDate: "2025-01-07T02:04:20.3199498-06:00",
        dateIssued: "2025-01-07T02:04:20.2932156-06:00",
        dateRegistered: "2025-01-07T02:04:20.2932156-06:00",
        expirationDate: null,
        memberId: 49083,
        isPrimary: true,
        linkKey: null,
        cardNumber: "1000000000123054",
        newStatus: null,
        newStatusEffectiveDate: null,
        status: "Active",
        statusChangeReason: null,
        updateDate: "2025-01-07T02:04:20.3199498-06:00",
        id: 48506,
        attributeSets: null,
      },
    ],
    attributeSets: [
      {
        memberDetails: [
          {
            id: 4902141,
            employeeType: "",
            employeeStatusChangeDate: null,
            employeeId: "",
            payType: "",
            isTaxExempt: null,
            isVeteran: null,
            isPermanentEmployee: null,
            enrollmentStoreId: null,
            secondaryPhoneNumber: "",
            communicationPreference: "B",
            smsOptInDate: "2021-03-08T11:00:00-06:00",
            plccAddressLineTwo: "",
            plccCity: "",
            plccStateOrProvince: "",
            plccZipOrPostalCode: "",
            plccFirstName: "",
            plccLastName: "",
            plccAddressLineOne: "",
            emailAddressMailable: null,
            memberStatusCode: null,
            directMailOptInDate: null,
            emailOptIn: true,
            addressLineThree: "",
            addressLineFour: "",
            county: "",
            country: "",
            addressMailable: null,
            secondaryEmailAddress: "",
            directMailOptIn: null,
            emailOptInDate: "2021-03-08T11:00:00-06:00",
            smsOptIn: true,
            smsDoubleOptInComplete: null,
            facebookOptIn: null,
            twitterOptIn: null,
            enrollDate: null,
            memberSource: 2,
            securityQuestion: "",
            securityAnswer: "",
            homeStoreID: null,
            termsAndConditionsAgreed: null,
            zipOrPostalCode: "",
            city: "",
            homePhone: "",
            smsConsentChangeDate: "2025-01-07T02:04:20.3668-06:00",
            facebookOptInDate: null,
            twitterOptInDate: null,
            gender: "",
            addressLineTwo: "",
            addressLineOne: "",
            stateOrProvince: "",
            mobilePhoneCountryCode: null,
            mobilePhone: "",
            workPhone: "",
            eReceiptPreference: null,
          },
        ],
        memberTermsCondition: [
          {
            id: 4902142,
            acceptanceDate: "2021-03-08T11:00:00-06:00",
            version: "v1 updated",
            isaccepted: false,
          },
        ],
        memberTaxExemption: [
          {
            id: 4902143,
            exemptionReasonLetter: "A",
            exemptionReason: "Wisconsin State or Local Government",
            exemptionType: "12",
            isActive: true,
            expirationDate: "2021-03-08T11:00:00-06:00",
            reviewDate: "2021-03-08T11:00:00-06:00",
          },
        ],
      },
    ],
    referralCode: "MYEVKUN",
  },
  developerMessage: "",
  userMessage: "Success",
  moreInfo: null,
  responseCode: 10000,
  httpStatusCode: 200,
  errors: null,
  requestId: "796bcdb5-d3c8-47c9-b32a-b002ed54cdb2",
};

export default customerCreatedResponse;